demoapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
urlpatterns = [
    path('polls/', include('polls.urls')),
    path('', views.home_page, name = 'Home_Page'),
    path('admin/', admin.site.urls),
]

polls/urls.py
from . import views
from django.urls import path

app_name = 'polls'
urlpatterns = [
    path('', views.hello_world, name='index'),
    path('departments/<int:department_id>', views.get_department, name='department_detail'),
    path('departments-detail', views.department_detail, name='departments_detail'),
    path('register', views.register_employee, name='employee_registration'),
    path('registration-done', views.registration_done, name='registration_done'),
]

polls/models.py
from django.db import models


class Department(models.Model):
    department_name = models.CharField(max_length=50)
    department_location = models.CharField(max_length=150)

    def __str__(self):
        return '{} in {}'.format(self.department_name, self.department_location)


class Employee(models.Model):
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    employee_name = models.CharField(max_length=60)

    def __str__(self):
        return self.employee_name

demoapp/views.py
from django.http import HttpResponse


def home_page(request):
    content = '''
    <h1>Welcome To my first Django App</h1>
    <b>This is the home page of my first web app.</b>
    <p>This is paragraph line, do you like the page?</p>
    
    '''
    return HttpResponse(content)

polls/views.py
from django.http import HttpResponse, Http404
from .models import Department, Employee
from django.template import loader
from django.shortcuts import get_object_or_404
from django.shortcuts import render
# Create your views here.


def hello_world(request):
    return HttpResponse('<h1>Hello World.<br>My first django app view.</h1>')


# def get_department(request, department_id):
#     try:
#
#         dep = Department.objects.get(pk=department_id)
#         dep = get_object_or_404(Department, pk=department_id)
#         output = '<h2>Details of department:</h2>' + f'<h3>Department Name:</h3><b>{dep.department_name}<b><br>' + \
#                  f'<h3>Department Location:</h3><b>{dep.department_location}<b><br>'
#         return HttpResponse(output)
#     except Department.DoesNotExist:
#         raise Http404('Department does not exist')


def get_department(request, department_id):

    # Other way to get department and raise error 404 if not exist
    dep = get_object_or_404(Department, pk=department_id)
    output = '<h2>Details of department:</h2>' + f'<h3>Department Name:</h3><b>{dep.department_name}<b><br>' + \
             f'<h3>Department Location:</h3><b>{dep.department_location}<b><br>'
    employees = Employee.objects.all()
    required_emp = []
    for emp in employees:
        if emp.department.id == department_id:
            required_emp.append(emp.employee_name)
    return HttpResponse(output + str(required_emp))


def department_detail(request):
    department_list = Department.objects.all()
    template = loader.get_template('polls/departments.html')
    context = {
       'department_list' : department_list
    }
    return HttpResponse(template.render(context, request))


def register_employee(request):

    department_list = Department.objects.all()
    context = {
        'department_list': department_list
    }
    return render(request, 'polls/add_employee.html', context)


def registration_done(request):
    dep = Department.objects.get(pk=request.POST['department'])
    emp = Employee(department=dep,
                   employee_name='{} {}'.format(request.POST["fname"], request.POST["lname"]))
    emp.save()
    return HttpResponse(f'<b>Name</b>:{request.POST["fname"]} {request.POST["lname"]}<br><b>Department:</b> {dep.department_name}')
    # return render(request, 'polls/registration_done.html', {})

polls/templates/polls/add_employee.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employee Registration</title>
</head>
<body>
<h1>Employee Registration</h1>

<form name="employee_registration" action="registration-done" method="post">
    <fieldset>
        <legend><h1>Registration Form</h1></legend>
    {% csrf_token %}
    First Name: <input type="text "  name="fname"><br><br>
    Last Name: <input type="text" name="lname"><br>
        {% for department in department_list %}
        <input type="radio" name="department"  value={{department.id}}>{{department.department_name}} <br>
        {% endfor %}
    <input type="submit" name="register">

    </fieldset>
</form>

</body>
</html>

polls/templates/polls/all_employees.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

polls/templates/polls/departments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Departments Detail</title>
</head>
<body>
<h1>All available departments are</h1>
{% if department_list %}
<ul>
    {% for department in department_list %}
    <!-- <li><a href="/polls/departments/{{department.id}}">{{department.department_name }}</a></li> -->
    <!-- Other and best way to do above task is -->
    <li><a href="{% url 'polls:department_detail' department.id %}" >{{department.department_name }}</a></li>
    {% endfor %}
</ul>
{% else %}
<rp>No Departments are available.</rp>
{% endif %}

</body>
</html>

polls/templates/polls/polls_main.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

polls/templates/polls/registration_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration Done</title>
</head>
<body>
<h1>You are registered Successfully.</h1>
</body>
</html>

polls/templates/polls/specific_department.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

polls/templates/polls/specific_employee.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>